#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDeClases
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Colegio")]
	public partial class OrmDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertalumno(alumno instance);
    partial void Updatealumno(alumno instance);
    partial void Deletealumno(alumno instance);
    partial void Insertcalificacion(calificacion instance);
    partial void Updatecalificacion(calificacion instance);
    partial void Deletecalificacion(calificacion instance);
    partial void Insertmateria(materia instance);
    partial void Updatemateria(materia instance);
    partial void Deletemateria(materia instance);
    partial void Insertprofesores(profesores instance);
    partial void Updateprofesores(profesores instance);
    partial void Deleteprofesores(profesores instance);
    #endregion
		
		public OrmDataContext() : 
				base(global::LibreriaDeClases.Properties.Settings.Default.ColegioConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public OrmDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<alumno> alumno
		{
			get
			{
				return this.GetTable<alumno>();
			}
		}
		
		public System.Data.Linq.Table<calificacion> calificacion
		{
			get
			{
				return this.GetTable<calificacion>();
			}
		}
		
		public System.Data.Linq.Table<materia> materia
		{
			get
			{
				return this.GetTable<materia>();
			}
		}
		
		public System.Data.Linq.Table<profesores> profesores
		{
			get
			{
				return this.GetTable<profesores>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="colegio.alumno")]
	public partial class alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodiAlumno;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Correo;
		
		private string _Clave;
		
		private EntitySet<calificacion> _calificacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiAlumnoChanging(int value);
    partial void OnCodiAlumnoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    #endregion
		
		public alumno()
		{
			this._calificacion = new EntitySet<calificacion>(new Action<calificacion>(this.attach_calificacion), new Action<calificacion>(this.detach_calificacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiAlumno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodiAlumno
		{
			get
			{
				return this._CodiAlumno;
			}
			set
			{
				if ((this._CodiAlumno != value))
				{
					this.OnCodiAlumnoChanging(value);
					this.SendPropertyChanging();
					this._CodiAlumno = value;
					this.SendPropertyChanged("CodiAlumno");
					this.OnCodiAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_calificacion", Storage="_calificacion", ThisKey="CodiAlumno", OtherKey="alumno_CodiAlumno")]
		public EntitySet<calificacion> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				this._calificacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_calificacion(calificacion entity)
		{
			this.SendPropertyChanging();
			entity.alumno = this;
		}
		
		private void detach_calificacion(calificacion entity)
		{
			this.SendPropertyChanging();
			entity.alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="colegio.calificacion")]
	public partial class calificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodiCalificacion;
		
		private System.Nullable<decimal> _Calificacion1;
		
		private string _Aprobo;
		
		private System.Nullable<System.DateTime> _FechaCalificacion;
		
		private int _Materia_CodiMateria;
		
		private int _alumno_CodiAlumno;
		
		private EntityRef<alumno> _alumno;
		
		private EntityRef<materia> _materia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiCalificacionChanging(int value);
    partial void OnCodiCalificacionChanged();
    partial void OnCalificacion1Changing(System.Nullable<decimal> value);
    partial void OnCalificacion1Changed();
    partial void OnAproboChanging(string value);
    partial void OnAproboChanged();
    partial void OnFechaCalificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCalificacionChanged();
    partial void OnMateria_CodiMateriaChanging(int value);
    partial void OnMateria_CodiMateriaChanged();
    partial void Onalumno_CodiAlumnoChanging(int value);
    partial void Onalumno_CodiAlumnoChanged();
    #endregion
		
		public calificacion()
		{
			this._alumno = default(EntityRef<alumno>);
			this._materia = default(EntityRef<materia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiCalificacion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodiCalificacion
		{
			get
			{
				return this._CodiCalificacion;
			}
			set
			{
				if ((this._CodiCalificacion != value))
				{
					this.OnCodiCalificacionChanging(value);
					this.SendPropertyChanging();
					this._CodiCalificacion = value;
					this.SendPropertyChanged("CodiCalificacion");
					this.OnCodiCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Calificacion", Storage="_Calificacion1", DbType="Decimal(1,1)")]
		public System.Nullable<decimal> Calificacion1
		{
			get
			{
				return this._Calificacion1;
			}
			set
			{
				if ((this._Calificacion1 != value))
				{
					this.OnCalificacion1Changing(value);
					this.SendPropertyChanging();
					this._Calificacion1 = value;
					this.SendPropertyChanged("Calificacion1");
					this.OnCalificacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aprobo", DbType="NVarChar(45)")]
		public string Aprobo
		{
			get
			{
				return this._Aprobo;
			}
			set
			{
				if ((this._Aprobo != value))
				{
					this.OnAproboChanging(value);
					this.SendPropertyChanging();
					this._Aprobo = value;
					this.SendPropertyChanged("Aprobo");
					this.OnAproboChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCalificacion", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCalificacion
		{
			get
			{
				return this._FechaCalificacion;
			}
			set
			{
				if ((this._FechaCalificacion != value))
				{
					this.OnFechaCalificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCalificacion = value;
					this.SendPropertyChanged("FechaCalificacion");
					this.OnFechaCalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia_CodiMateria", DbType="Int NOT NULL")]
		public int Materia_CodiMateria
		{
			get
			{
				return this._Materia_CodiMateria;
			}
			set
			{
				if ((this._Materia_CodiMateria != value))
				{
					if (this._materia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateria_CodiMateriaChanging(value);
					this.SendPropertyChanging();
					this._Materia_CodiMateria = value;
					this.SendPropertyChanged("Materia_CodiMateria");
					this.OnMateria_CodiMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_CodiAlumno", DbType="Int NOT NULL")]
		public int alumno_CodiAlumno
		{
			get
			{
				return this._alumno_CodiAlumno;
			}
			set
			{
				if ((this._alumno_CodiAlumno != value))
				{
					if (this._alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalumno_CodiAlumnoChanging(value);
					this.SendPropertyChanging();
					this._alumno_CodiAlumno = value;
					this.SendPropertyChanged("alumno_CodiAlumno");
					this.Onalumno_CodiAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumno_calificacion", Storage="_alumno", ThisKey="alumno_CodiAlumno", OtherKey="CodiAlumno", IsForeignKey=true)]
		public alumno alumno
		{
			get
			{
				return this._alumno.Entity;
			}
			set
			{
				alumno previousValue = this._alumno.Entity;
				if (((previousValue != value) 
							|| (this._alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alumno.Entity = null;
						previousValue.calificacion.Remove(this);
					}
					this._alumno.Entity = value;
					if ((value != null))
					{
						value.calificacion.Add(this);
						this._alumno_CodiAlumno = value.CodiAlumno;
					}
					else
					{
						this._alumno_CodiAlumno = default(int);
					}
					this.SendPropertyChanged("alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="materia_calificacion", Storage="_materia", ThisKey="Materia_CodiMateria", OtherKey="CodiMateria", IsForeignKey=true)]
		public materia materia
		{
			get
			{
				return this._materia.Entity;
			}
			set
			{
				materia previousValue = this._materia.Entity;
				if (((previousValue != value) 
							|| (this._materia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._materia.Entity = null;
						previousValue.calificacion.Remove(this);
					}
					this._materia.Entity = value;
					if ((value != null))
					{
						value.calificacion.Add(this);
						this._Materia_CodiMateria = value.CodiMateria;
					}
					else
					{
						this._Materia_CodiMateria = default(int);
					}
					this.SendPropertyChanged("materia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="colegio.materia")]
	public partial class materia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodiMateria;
		
		private string _NombreMate;
		
		private int _profesores_IdentiProfe;
		
		private EntitySet<calificacion> _calificacion;
		
		private EntityRef<profesores> _profesores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiMateriaChanging(int value);
    partial void OnCodiMateriaChanged();
    partial void OnNombreMateChanging(string value);
    partial void OnNombreMateChanged();
    partial void Onprofesores_IdentiProfeChanging(int value);
    partial void Onprofesores_IdentiProfeChanged();
    #endregion
		
		public materia()
		{
			this._calificacion = new EntitySet<calificacion>(new Action<calificacion>(this.attach_calificacion), new Action<calificacion>(this.detach_calificacion));
			this._profesores = default(EntityRef<profesores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiMateria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodiMateria
		{
			get
			{
				return this._CodiMateria;
			}
			set
			{
				if ((this._CodiMateria != value))
				{
					this.OnCodiMateriaChanging(value);
					this.SendPropertyChanging();
					this._CodiMateria = value;
					this.SendPropertyChanged("CodiMateria");
					this.OnCodiMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMate", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string NombreMate
		{
			get
			{
				return this._NombreMate;
			}
			set
			{
				if ((this._NombreMate != value))
				{
					this.OnNombreMateChanging(value);
					this.SendPropertyChanging();
					this._NombreMate = value;
					this.SendPropertyChanged("NombreMate");
					this.OnNombreMateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profesores_IdentiProfe", DbType="Int NOT NULL")]
		public int profesores_IdentiProfe
		{
			get
			{
				return this._profesores_IdentiProfe;
			}
			set
			{
				if ((this._profesores_IdentiProfe != value))
				{
					if (this._profesores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprofesores_IdentiProfeChanging(value);
					this.SendPropertyChanging();
					this._profesores_IdentiProfe = value;
					this.SendPropertyChanged("profesores_IdentiProfe");
					this.Onprofesores_IdentiProfeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="materia_calificacion", Storage="_calificacion", ThisKey="CodiMateria", OtherKey="Materia_CodiMateria")]
		public EntitySet<calificacion> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				this._calificacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profesores_materia", Storage="_profesores", ThisKey="profesores_IdentiProfe", OtherKey="IdentiProfe", IsForeignKey=true)]
		public profesores profesores
		{
			get
			{
				return this._profesores.Entity;
			}
			set
			{
				profesores previousValue = this._profesores.Entity;
				if (((previousValue != value) 
							|| (this._profesores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._profesores.Entity = null;
						previousValue.materia.Remove(this);
					}
					this._profesores.Entity = value;
					if ((value != null))
					{
						value.materia.Add(this);
						this._profesores_IdentiProfe = value.IdentiProfe;
					}
					else
					{
						this._profesores_IdentiProfe = default(int);
					}
					this.SendPropertyChanged("profesores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_calificacion(calificacion entity)
		{
			this.SendPropertyChanging();
			entity.materia = this;
		}
		
		private void detach_calificacion(calificacion entity)
		{
			this.SendPropertyChanging();
			entity.materia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="colegio.profesores")]
	public partial class profesores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdentiProfe;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private int _Edad;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Clave;
		
		private EntitySet<materia> _materia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdentiProfeChanging(int value);
    partial void OnIdentiProfeChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnEdadChanging(int value);
    partial void OnEdadChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    #endregion
		
		public profesores()
		{
			this._materia = new EntitySet<materia>(new Action<materia>(this.attach_materia), new Action<materia>(this.detach_materia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentiProfe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdentiProfe
		{
			get
			{
				return this._IdentiProfe;
			}
			set
			{
				if ((this._IdentiProfe != value))
				{
					this.OnIdentiProfeChanging(value);
					this.SendPropertyChanging();
					this._IdentiProfe = value;
					this.SendPropertyChanged("IdentiProfe");
					this.OnIdentiProfeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this.OnEdadChanging(value);
					this.SendPropertyChanging();
					this._Edad = value;
					this.SendPropertyChanged("Edad");
					this.OnEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(90) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profesores_materia", Storage="_materia", ThisKey="IdentiProfe", OtherKey="profesores_IdentiProfe")]
		public EntitySet<materia> materia
		{
			get
			{
				return this._materia;
			}
			set
			{
				this._materia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_materia(materia entity)
		{
			this.SendPropertyChanging();
			entity.profesores = this;
		}
		
		private void detach_materia(materia entity)
		{
			this.SendPropertyChanging();
			entity.profesores = null;
		}
	}
}
#pragma warning restore 1591
